### ISSUE TITLE
The link of model weight of AOT with Swin-L is expired

### ISSUE THREAD

**Issue by bo-miao** [Zhiweihhh/cvpr2022-rvos-challenge#1]
Hi, 

Thanks for the interesting work. 
The link of the model weight of AOT with Swin-L is expired. May I have the checkpoint?

**Comment by Zhiweihhh** [comment]
Hi @bo-miao 
We have checked the link and it is still available for download. All of our pretrained models are available for download at [AOT](https://github.com/yoxu515/aot-benchmark/blob/main/MODEL_ZOO.md) and [ReferFormer](https://github.com/wjn922/referformer), and our trained models for AOT can be downloaded [here](https://drive.google.com/file/d/13Fq7DhQETxCRPkU53ggLSWYn4-qrPz8V/view?usp=sharing).

**Comment by bo-miao** [comment]
Excellent. Thanks.

The link I previously clicked is "You can also download our model [here](https://github.com/Zhiweihhh/cvpr2022-rvos-challenge/blob/main)."
